recaptcha {
    // These keys are generated by the ReCaptcha service
	publicKey = "6LdT1NMSAAAAALhmzuDQac-arK8H14s1vZtyX1l9"
	privateKey = "6LdT1NMSAAAAAIIjP1EcQ-v5uhYAOeSLA6xLD-cr"

	// Include the noscript tags in the generated captcha
	includeNoScript = true
}

mailhide {
    // Generated by the Mailhide service
    publicKey = ""
    privateKey = ""
}

environments {
  development {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = false
    }
  }
  production {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = true
    }
  }
  saturn {
	  recaptcha {
		// Set to false to disable the display of captcha
		enabled = true
  
		// Communicate using HTTPS
		useSecureAPI = true
	  }
	}
  pamba {
	  recaptcha {
		// Set to false to disable the display of captcha
		enabled = true
  
		// Communicate using HTTPS
		useSecureAPI = true
	  }
	}
}